name: gmt_planter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: 2.5.0
  connectivity: 2.0.2
  cupertino_icons: 1.0.2
  dio: 3.0.10
  flutter_hooks: 0.15.0
  flutter_platform_widgets: 0.72.0
  flutter_svg: 0.19.2+1
  provider: 4.3.2+3
  shared_preferences: 0.5.12+4
  url_launcher: 5.7.10
  velocity_x: 1.3.1
  image_picker: 0.6.7+20
  camera: 0.7.0+1
  permission_handler: 5.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.12
  lint: 1.5.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
