name: gmt_planter
description: A new Flutter project.

publish_to: "none"

version: 1.0.6+16

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: 3.2.0
  camera: 0.9.4+14
  connectivity: 3.0.6
  cupertino_icons: 1.0.4
  dio: 4.0.4
  firebase_core: 1.12.0
  firebase_messaging: 11.2.6
  flutter:
    sdk: flutter
  flutter_hooks: 0.18.2+1
  flutter_local_notifications: 9.3.2
  flutter_localizations:
    sdk: flutter
  flutter_platform_widgets: 1.10.0
  flutter_svg: 1.0.3
  image_picker: 0.8.4+9
  intl: 0.17.0
  package_info: 2.0.2
  path_provider: 2.0.9
  permission_handler: 8.3.0
  provider: 6.0.2
  shared_preferences: 2.0.13
  url_launcher: 6.0.20
  velocity_x: 3.4.0
  image_cropper: 1.5.0

dependency_overrides:
  platform: ^3.1.0

dev_dependencies:
  rename: ^2.0.1
  flutter_launcher_icons: 0.9.2
  flutter_test:
    sdk: flutter
  lint: 1.8.2
flutter_icons:
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/language/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
