name: gmt_planter
description: A new Flutter project.

publish_to: "none"

version: 1.0.6+16

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: 3.1.0+1
  camera: 0.9.4+3
  connectivity: 3.0.6
  cupertino_icons: 1.0.4
  dio: 4.0.1
  firebase_core: 1.10.0
  firebase_messaging: 11.1.0
  flutter:
    sdk: flutter
  flutter_hooks: 0.18.1
  flutter_local_notifications: 9.1.0
  exif: 3.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_image: 0.0.6+1
  flutter_platform_widgets: 1.10.0
  flutter_svg: 0.23.0+1
  image: 3.0.8
  image_picker: 0.8.4+4
  package_info: 2.0.2
  path_provider: 2.0.6
  permission_handler: 8.2.6
  provider: 6.0.1
  shared_preferences: 2.0.8
  url_launcher: 6.0.12
  velocity_x: 3.3.0

dev_dependencies:
  change_app_package_name: 1.0.0
  flutter_launcher_icons: 0.9.2
  flutter_test:
    sdk: flutter
  lint: 1.7.2
flutter_icons:
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/language/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
