name: gmt_planter
description: A new Flutter project.

publish_to: "none"

version: 1.0.4+14

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: 3.1.0
  camera: 0.9.3+1
  connectivity: 3.0.6
  cupertino_icons: 1.0.3
  dio: 4.0.0
  firebase_core: 1.6.0
  firebase_messaging: 10.0.7
  flutter:
    sdk: flutter
  flutter_hooks: 0.18.0
  flutter_local_notifications: 8.2.0
  flutter_localizations:
    sdk: flutter
  flutter_native_image: 0.0.6+1
  flutter_platform_widgets: 1.9.5
  flutter_svg: 0.22.0
  image: 3.0.4
  image_picker: 0.8.4+2
  package_info: 2.0.2
  path_provider: 2.0.5
  permission_handler: 8.1.6
  provider: 6.0.0
  shared_preferences: 2.0.8
  url_launcher: 6.0.11
  velocity_x: 3.3.0

dev_dependencies:
  change_app_package_name: 1.0.0
  flutter_launcher_icons: 0.9.2
  flutter_test:
    sdk: flutter
  lint: 1.7.2
flutter_icons:
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/language/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
