name: gmt_planter
description: A new Flutter project.

publish_to: "none"

version: 0.0.8+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  velocity_x:
    git:
      url: https://github.com/iampawan/VelocityX
      ref: dev#null-safety
  cached_network_image: 3.0.0-nullsafety
  camera: 0.8.0
  connectivity: 3.0.2
  cupertino_icons: 1.0.2
  dio: 4.0.0-beta6
  firebase_core: 1.3.0
  firebase_messaging: 10.0.2
  flutter_hooks: 0.16.0
  flutter_platform_widgets: 1.0.1-nullsafety.0
  flutter_svg: 0.21.0-nullsafety.0
  image_picker: 0.7.2
  package_info: 2.0.2
  path_provider: 2.0.1
  permission_handler: 6.0.1
  provider: 5.0.0
  shared_preferences: 2.0.1
  url_launcher: 6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: 1.0.0
  flutter_launcher_icons: 0.9.0
  lint: 1.5.1
flutter_icons:
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/language/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
